//go:build windows

package etw

import (
	"runtime"
	"strings"
	"syscall"
	"unsafe"
)

// ProviderFilter is an interface for various ETW filters that can be applied when enabling a provider.
//
// These filters are typically applied by the ETW runtime *after* an event has been
// generated by its provider. This is in contrast to Level/Keyword filtering, which
// happens inside the provider *before* an event is generated.
//
// Consequently, using these filters is effective for reducing the volume of data
// in a trace, but it does not reduce the initial CPU overhead of event creation.
//
// Example usage:
//
//	Filters: []etw.ProviderFilter{
//		etw.NewEventIDFilter(true, 10, 11),
//		etw.NewPIDFilter(1234, 5678),                             // read doc about limitations
//		etw.NewExecutableNameFilter("svchost.exe","conhost.exe"), // read doc about limitations
//		etw.NewEventNameFilter(true, "MyEventName"),
//		etw.NewEventLevelKWFilter(true, 5, 0x10, 0),     // stackwalk filter based on level and keyword
//		etw.NewStackWalkFilter(true, 10, 11),            // stackwalk filter based on event IDs
//		etw.NewStackWalkNameFilter(true, "MyEventName"), // stackwalk filter based on event name
//
//		// Advanced Filters:
//		// Payload filters allow filtering based on the actual content of the event.
//		etw.NewPayloadFilter(
//			providerGUID,
//			false, // matchAll
//			etw.PayloadFilterEvent{
//				EventDescriptor: etw.EventDescriptor{Id: 1},
//				MatchAny:        false,
//				Predicates: []etw.PayloadPredicate{
//					{Field: "ImageName", CompareOp: etw.PAYLOADFIELD_CONTAINS, Value: "notepad.exe"},
//				},
//			},
//		),
//		// Schematized filters use binary data defined in the provider's manifest.
//		etw.NewSchematizedFilter(1, 0, []byte{0x01, 0x02, 0x03}),
//	},
type ProviderFilter interface {
	// build allocates the necessary C structures and returns a descriptor.
	build() (desc EventFilterDescriptor, keepAlive any)
}

// --- Concrete Filter Implementations ---

// EventIDFilter filters events based on their 16-bit event ID.
//
// # CPU Performance Impact: Medium
//
// This is an "attribute filter" that is applied by the ETW runtime *after* the
// provider has already generated the event and sent it to ETW. This means the
// CPU cost of creating the event has already been paid.
//
// This type of filtering is effective for reducing the volume of trace data
// written to the session buffers, but it is not effective for reducing the
// initial CPU overhead of event generation on the provider side.
//
// When applied to a TraceLogging provider, this filter will be ignored as
// TraceLogging events do not have static event IDs.
//
// The maximum number of event IDs allowed is limited by MAX_EVENT_FILTER_EVENT_ID_COUNT (64).
type EventIDFilter struct {
	IDs      []uint16
	FilterIn bool // True (default) to include these IDs, false to exclude them.
}

// NewEventIDFilter creates a new filter for the given event IDs.
// `filterIn` determines whether to include (true) or exclude (false) events with these IDs.
func NewEventIDFilter(filterIn bool, ids ...uint16) *EventIDFilter {
	return &EventIDFilter{IDs: ids, FilterIn: filterIn}
}

func (f *EventIDFilter) build() (EventFilterDescriptor, any) {
	// LIMIT: MAX_EVENT_FILTER_EVENT_ID_COUNT (64)
	if len(f.IDs) == 0 || len(f.IDs) > MAX_EVENT_FILTER_EVENT_ID_COUNT {
		return EventFilterDescriptor{}, nil
	}

	// keepAlive holds a reference to the allocated go memory so that uintptr cast survives
	filterData, keepAlive := AllocEventFilterEventID(f.IDs)
	if f.FilterIn {
		filterData.FilterIn = 1
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(filterData))),
		Size: uint32(filterData.Size()),
		Type: EVENT_FILTER_TYPE_EVENT_ID,
	}, keepAlive // Pass the keeapalive pointer up to the caller.
}

// PIDFilter filters events based on the Process ID (PID) of the originating process.
//
// # CPU Performance Impact: Low
//
// This is a "scope filter" and is highly efficient. According to Microsoft's
// documentation, providers disabled by scope filters have "almost no impact on
// system performance". This is because the ETW runtime can prevent the provider
// from being enabled within the specified processes altogether, avoiding the CPU
// cost of event generation from those processes entirely.
//
// # Kernel Provider Limitation
//
// This has a critical implication for Kernel Providers (e.g., "Microsoft-Windows-Kernel-Process"):
// The provider is the kernel itself (PID 4 or 0). When a PID filter for a user-mode
// process is applied to a kernel provider, the ETW subsystem appears to IGNORE the
// filter. Events will still be received from the provider as if no PID filter was applied.
//
// The maximum number of PIDs that can be filtered is limited by MAX_EVENT_FILTER_PID_COUNT (8).
type PIDFilter struct {
	PIDs []uint32
}

// NewPIDFilter creates a new filter for the given process IDs. A maximum of 8 PIDs can be supplied.
func NewPIDFilter(pids ...uint32) *PIDFilter {
	return &PIDFilter{PIDs: pids}
}

func (f *PIDFilter) build() (EventFilterDescriptor, any) {
	// LIMIT: MAX_EVENT_FILTER_PID_COUNT (8)
	if len(f.PIDs) == 0 || len(f.PIDs) > MAX_EVENT_FILTER_PID_COUNT {
		return EventFilterDescriptor{}, nil
	}

	// Create a copy that is kept alive.
	pidCopy := make([]uint32, len(f.PIDs))
	copy(pidCopy, f.PIDs)

	desc := EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(&pidCopy[0]))),
		Size: uint32(len(pidCopy) * 4),
		Type: EVENT_FILTER_TYPE_PID,
	}

	// Return a pointer to the original slice. This is the simplest and safest object to keep alive.
	return desc, &pidCopy
}

// ExecutableNameFilter filters events based on the file name of the originating process.
//
// # CPU Performance Impact: Low
//
// This is a "scope filter" and is highly efficient for the same reasons as the
// PIDFilter. It can prevent a provider from being enabled within processes matching
// the given executable names, which avoids the CPU cost of event generation.
//
// # Kernel Provider Limitation
//
// This filter is generally ignored when used with Kernel Providers, similar to the PIDFilter.
//
// The filter is a single string that can contain multiple executable file names
// separated by semicolons (e.g., "svchost.exe;conhost.exe").
type ExecutableNameFilter struct {
	Names []string
}

// NewExecutableNameFilter creates a new filter for the given executable names (e.g., "svchost.exe").
func NewExecutableNameFilter(names ...string) *ExecutableNameFilter {
	return &ExecutableNameFilter{Names: names}
}

func (f *ExecutableNameFilter) build() (EventFilterDescriptor, any) {
	if len(f.Names) == 0 {
		return EventFilterDescriptor{}, nil
	}

	joined := strings.Join(f.Names, ";")
	// The API expects a null-terminated wide string (UTF-16).
	utf16Str, err := syscall.UTF16FromString(joined)
	if err != nil {
		return EventFilterDescriptor{}, nil
	}

	// LIMIT: MAX_EVENT_FILTER_DATA_SIZE (1024)
	size := uint32(len(utf16Str) * 2) // size in bytes, including null terminator
	if size > MAX_EVENT_FILTER_DATA_SIZE {
		return EventFilterDescriptor{}, nil
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(&utf16Str[0]))),
		Size: size,
		Type: EVENT_FILTER_TYPE_EXECUTABLE_NAME,
	}, &utf16Str
}

// EventNameFilter filters TraceLogging events based on their names.
//
// # CPU Performance Impact: Medium
//
// This is an "attribute filter" applied by the ETW runtime to TraceLogging providers.
// It allows enabling or disabling specific events by name, further refined by
// level and keywords.
//
// If applied to a non-TraceLogging provider, this filter is ignored.
type EventNameFilter struct {
	Names           []string
	MatchAnyKeyword uint64
	MatchAllKeyword uint64
	Level           uint8
	FilterIn        bool // True to include these names, false to exclude them.
}

// NewEventNameFilter creates a new filter for the given TraceLogging event names.
// If filterIn is true, only events with these names are captured; otherwise, they are excluded.
func NewEventNameFilter(filterIn bool, names ...string) *EventNameFilter {
	return &EventNameFilter{
		Names:    names,
		FilterIn: filterIn,
	}
}

func (f *EventNameFilter) build() (EventFilterDescriptor, any) {
	filter, totalSize, keepAlive := AllocEventFilterEventName(f.Names)
	// LIMIT: MAX_EVENT_FILTER_EVENT_NAME_SIZE (4096)
	if filter == nil || totalSize > MAX_EVENT_FILTER_EVENT_NAME_SIZE {
		return EventFilterDescriptor{}, nil
	}

	// Set the remaining filter criteria
	filter.MatchAnyKeyword = f.MatchAnyKeyword
	filter.MatchAllKeyword = f.MatchAllKeyword
	filter.Level = f.Level
	if f.FilterIn {
		filter.FilterIn = 1
	} else {
		filter.FilterIn = 0
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(filter))),
		Size: uint32(totalSize),
		Type: EVENT_FILTER_TYPE_EVENT_NAME,
	}, keepAlive
}

// EventLevelKWFilter filters stack collection based on event level and keywords.
//
// # CPU Performance Impact: Low (for the filter itself)
//
// This filter determines whether a stack trace should be captured for events
// matching the specified level and keyword bitmasks.
//
// Note: To actually collect stacks, you must also specify
// EVENT_ENABLE_PROPERTY_STACK_TRACE in the ENABLE_TRACE_PARAMETERS structure.
type EventLevelKWFilter struct {
	MatchAnyKeyword uint64
	MatchAllKeyword uint64
	Level           uint8
	FilterIn        bool // True to collect stacks for matching events, false to disable.
}

// NewEventLevelKWFilter creates a new filter for stack collection based on level and keywords.
func NewEventLevelKWFilter(filterIn bool, level uint8, anyKW, allKW uint64) *EventLevelKWFilter {
	return &EventLevelKWFilter{
		FilterIn:        filterIn,
		Level:           level,
		MatchAnyKeyword: anyKW,
		MatchAllKeyword: allKW,
	}
}

func (f *EventLevelKWFilter) build() (EventFilterDescriptor, any) {
	filter := &EventFilterLevelKW{
		MatchAnyKeyword: f.MatchAnyKeyword,
		MatchAllKeyword: f.MatchAllKeyword,
		Level:           f.Level,
	}

	if f.FilterIn {
		filter.FilterIn = 1
	} else {
		filter.FilterIn = 0
	}

	// LIMIT: MAX_EVENT_FILTER_DATA_SIZE (1024)
	size := uint32(unsafe.Sizeof(*filter))
	if size > MAX_EVENT_FILTER_DATA_SIZE {
		return EventFilterDescriptor{}, nil
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(filter))),
		Size: size,
		Type: EVENT_FILTER_TYPE_STACKWALK_LEVEL_KW,
	}, filter // The struct itself acts as the keepAlive object
}

// StackWalkFilter filters stack collection based on specific event IDs.
//
// # CPU Performance Impact: Low
//
// This filter determines whether a stack trace should be captured for specific
// event IDs. Each event write call will go through this array quickly to find
// out whether the stack should be captured or not.
//
// When applied to a TraceLogging provider, this filter will be ignored as
// TraceLogging events do not have static event IDs.
//
// Note: To actually collect stacks, you must also specify
// EVENT_ENABLE_PROPERTY_STACK_TRACE in the EnableProperties of the Provider.
//
// The maximum number of event IDs allowed is limited by MAX_EVENT_FILTER_EVENT_ID_COUNT (64).
type StackWalkFilter struct {
	IDs      []uint16
	FilterIn bool // True to collect stacks for these IDs, false to disable.
}

// NewStackWalkFilter creates a new filter for stack collection based on specific event IDs.
func NewStackWalkFilter(filterIn bool, ids ...uint16) *StackWalkFilter {
	return &StackWalkFilter{IDs: ids, FilterIn: filterIn}
}

func (f *StackWalkFilter) build() (EventFilterDescriptor, any) {
	// LIMIT: MAX_EVENT_FILTER_EVENT_ID_COUNT (64)
	if len(f.IDs) == 0 || len(f.IDs) > MAX_EVENT_FILTER_EVENT_ID_COUNT {
		return EventFilterDescriptor{}, nil
	}

	// We reuse the EventID allocator since it's the exact same struct layout
	filterData, keepAlive := AllocEventFilterEventID(f.IDs)
	if f.FilterIn {
		filterData.FilterIn = 1
	} else {
		filterData.FilterIn = 0
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(filterData))),
		Size: uint32(filterData.Size()),
		Type: EVENT_FILTER_TYPE_STACKWALK,
	}, keepAlive
}

// StackWalkNameFilter filters stack collection for TraceLogging events based on their names.
//
// # CPU Performance Impact: Low
//
// This feature allows filtering of stack collection for TraceLogging events based on
// the event names. You can further refine it using Keyword bitmasks and Level.
//
// When applied to a non-TraceLogging provider, this filter is ignored as those
// events do not have names specified in their payload.
//
// Note: To actually collect stacks, you must also specify
// EVENT_ENABLE_PROPERTY_STACK_TRACE in the EnableProperties of the Provider.
type StackWalkNameFilter struct {
	Names           []string
	MatchAnyKeyword uint64
	MatchAllKeyword uint64
	Level           uint8
	FilterIn        bool // True to collect stacks for matching events, false to disable.
}

// NewStackWalkNameFilter creates a new filter for stack collection based on TraceLogging event names.
func NewStackWalkNameFilter(filterIn bool, names ...string) *StackWalkNameFilter {
	return &StackWalkNameFilter{
		Names:    names,
		FilterIn: filterIn,
	}
}

func (f *StackWalkNameFilter) build() (EventFilterDescriptor, any) {
	// We reuse the EventName allocator since it's the exact same struct layout
	filter, totalSize, keepAlive := AllocEventFilterEventName(f.Names)
	// LIMIT: MAX_EVENT_FILTER_EVENT_NAME_SIZE (4096)
	if filter == nil || totalSize > MAX_EVENT_FILTER_EVENT_NAME_SIZE {
		return EventFilterDescriptor{}, nil
	}

	filter.MatchAnyKeyword = f.MatchAnyKeyword
	filter.MatchAllKeyword = f.MatchAllKeyword
	filter.Level = f.Level
	if f.FilterIn {
		filter.FilterIn = 1
	} else {
		filter.FilterIn = 0
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(filter))),
		Size: uint32(totalSize),
		Type: EVENT_FILTER_TYPE_STACKWALK_NAME, // Specify this is a StackWalk Name filter
	}, keepAlive
}

// PayloadPredicate defines a single condition for a payload filter.
type PayloadPredicate struct {
	Field     string // Name of the field in the manifest (e.g., "ImageName")
	CompareOp uint16 // Use PAYLOADFIELD_* constants (e.g., PAYLOADFIELD_CONTAINS)
	Value     string // The value to compare against. Always represented as a string.
}

// PayloadFilterEvent defines a set of predicates for a specific event descriptor.
type PayloadFilterEvent struct {
	EventDescriptor EventDescriptor
	MatchAny        bool // True = Write event if ANY predicate matches (OR). False = Must match ALL (AND).
	Predicates      []PayloadPredicate
}

// PayloadFilter filters events based on their payload content.
//
// # CPU Performance Impact: Medium to High
//
// This filter evaluates the actual binary payload of the event. It leverages the
// Windows TDH API to compile predicates into a highly efficient binary filter blob.
//
// The maximum data size for an event payload filter is limited to MAX_EVENT_FILTER_PAYLOAD_SIZE (4096).
type PayloadFilter struct {
	ProviderGUID GUID
	MatchAll     bool // True = Must match all PayloadFilterEvents. False = Match any.
	Events       []PayloadFilterEvent
}

// NewPayloadFilter creates a new, functional payload filter.
// It abstracts the complexity of TdhCreatePayloadFilter and TdhAggregatePayloadFilters.
func NewPayloadFilter(providerGUID GUID, matchAll bool, events ...PayloadFilterEvent) *PayloadFilter {
	return &PayloadFilter{
		ProviderGUID: providerGUID,
		MatchAll:     matchAll,
		Events:       events,
	}
}

// payloadFilterCleanup handles freeing unmanaged C memory allocated by TDH.
type payloadFilterCleanup struct {
	aggregatedDesc *EventFilterDescriptor
	singleFilters  []unsafe.Pointer
}

// Free is called automatically by EnableProvider once the API call is done.
func (c *payloadFilterCleanup) Free() {
	if c.aggregatedDesc != nil {
		TdhCleanupPayloadEventFilterDescriptor(c.aggregatedDesc)
	}
	for _, ptr := range c.singleFilters {
		TdhDeletePayloadFilter(&ptr)
	}
}

func (f *PayloadFilter) build() (EventFilterDescriptor, any) {
	// Initialize cleanup to track unmanaged C memory allocated by TDH.
	cleanup := &payloadFilterCleanup{}
	if len(f.Events) == 0 {
		return EventFilterDescriptor{}, cleanup
	}

	var singleFilters []unsafe.Pointer

	for _, evt := range f.Events {
		if len(evt.Predicates) == 0 {
			continue
		}

		var cPreds []PayloadFilterPredicate
		// Retain UTF-16 pointers to prevent GC movement during the syscall.
		var keepStrings []any

		for _, p := range evt.Predicates {
			fName, _ := syscall.UTF16PtrFromString(p.Field)
			val, _ := syscall.UTF16PtrFromString(p.Value)
			cPreds = append(cPreds, PayloadFilterPredicate{
				FieldName: fName,
				CompareOp: p.CompareOp,
				Value:     val,
			})
			keepStrings = append(keepStrings, fName, val)
		}

		var singlePtr unsafe.Pointer
		// Compile predicates into an opaque binary blob for a single event.
		err := TdhCreatePayloadFilter(
			&f.ProviderGUID,
			&evt.EventDescriptor,
			evt.MatchAny,
			uint32(len(cPreds)),
			&cPreds[0],
			&singlePtr,
		)
		runtime.KeepAlive(keepStrings)

		// Only add successful compilations to aggregation
		if err == nil && singlePtr != nil {
			singleFilters = append(singleFilters, singlePtr)
		}
	}

	cleanup.singleFilters = singleFilters

	if len(singleFilters) == 0 {
		return EventFilterDescriptor{}, cleanup
	}

	var aggregatedDesc EventFilterDescriptor
	matchAll := f.MatchAll
	// Aggregate individual event filters into a single descriptor for EnableTraceEx2.
	err := TdhAggregatePayloadFilters(
		uint32(len(singleFilters)),
		&singleFilters[0],
		&matchAll,
		&aggregatedDesc,
	)

	if err != nil {
		return EventFilterDescriptor{}, cleanup
	}

	cleanup.aggregatedDesc = &aggregatedDesc
	// Return the descriptor and the cleaner to ensure memory is freed after the provider is enabled.
	return aggregatedDesc, cleanup
}

// SchematizedFilter represents a traditional provider-side filter defined in the manifest.
//
// # CPU Performance Impact: Low
//
// The controller defines a custom set of filters as a binary object. The provider
// interprets this object and filters events *before* writing them, making it
// highly efficient.
type SchematizedFilter struct {
	Id      uint16
	Version uint8
	Data    []byte // The custom binary data following the header
}

// NewSchematizedFilter creates a new schematized filter.
// Use TdhEnumerateProviderFilters to retrieve the filters defined in a manifest.
func NewSchematizedFilter(id uint16, version uint8, data []byte) *SchematizedFilter {
	return &SchematizedFilter{
		Id:      id,
		Version: version,
		Data:    data,
	}
}

func (f *SchematizedFilter) build() (EventFilterDescriptor, any) {
	headerSize := uint32(unsafe.Sizeof(EventFilterHeader{}))
	totalSize := headerSize + uint32(len(f.Data))

	// LIMIT: MAX_EVENT_FILTER_DATA_SIZE (1024)
	if totalSize > MAX_EVENT_FILTER_DATA_SIZE {
		return EventFilterDescriptor{}, nil
	}

	buf := make([]byte, totalSize)
	header := (*EventFilterHeader)(unsafe.Pointer(&buf[0]))

	header.Id = f.Id
	header.Version = f.Version
	header.Size = totalSize
	// ETW documentation states: "the session must set InstanceId and NextOffset to zero"
	header.InstanceId = 0
	header.NextOffset = 0

	if len(f.Data) > 0 {
		copy(buf[headerSize:], f.Data)
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(&buf[0]))),
		Size: totalSize,
		Type: EVENT_FILTER_TYPE_SCHEMATIZED,
	}, &buf
}

// PackageIDFilter filters events emitted from a particular Windows Store app package.
//
// # CPU Performance Impact: Low
//
// This is a "scope filter". It will only enable the provider for the specified
// App Package IDs.
//
// The filter accepts multiple Package IDs, which will be separated by semicolons internally.
type PackageIDFilter struct {
	PackageIDs []string
}

// NewPackageIDFilter creates a new filter for the given Windows Store Package IDs.
func NewPackageIDFilter(packageIDs ...string) *PackageIDFilter {
	return &PackageIDFilter{PackageIDs: packageIDs}
}

func (f *PackageIDFilter) build() (EventFilterDescriptor, any) {
	if len(f.PackageIDs) == 0 {
		return EventFilterDescriptor{}, nil
	}

	joined := strings.Join(f.PackageIDs, ";")
	utf16Str, err := syscall.UTF16FromString(joined)
	if err != nil {
		return EventFilterDescriptor{}, nil
	}

	// LIMIT: MAX_EVENT_FILTER_DATA_SIZE (1024)
	size := uint32(len(utf16Str) * 2) // size in bytes, including null terminator
	if size > MAX_EVENT_FILTER_DATA_SIZE {
		return EventFilterDescriptor{}, nil
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(&utf16Str[0]))),
		Size: size,
		Type: EVENT_FILTER_TYPE_PACKAGE_ID,
	}, &utf16Str
}

// PackageAppIDFilter filters events emitted from a particular Package Relative App ID (PRAID).
//
// # CPU Performance Impact: Low
//
// This is a "scope filter". It will only enable the provider for the specified PRAIDs.
//
// The filter accepts multiple PRAID, which will be separated by semicolons internally.
type PackageAppIDFilter struct {
	AppIDs []string
}

// NewPackageAppIDFilter creates a new filter for the given Package Relative App IDs (PRAID).
// This can be used to filter providers to events emitted from a particular Windows Store app package.
func NewPackageAppIDFilter(appIDs ...string) *PackageAppIDFilter {
	return &PackageAppIDFilter{AppIDs: appIDs}
}

func (f *PackageAppIDFilter) build() (EventFilterDescriptor, any) {
	if len(f.AppIDs) == 0 {
		return EventFilterDescriptor{}, nil
	}

	joined := strings.Join(f.AppIDs, ";")
	utf16Str, err := syscall.UTF16FromString(joined)
	if err != nil {
		return EventFilterDescriptor{}, nil
	}

	// LIMIT: MAX_EVENT_FILTER_DATA_SIZE (1024)
	size := uint32(len(utf16Str) * 2) // size in bytes, including null terminator
	if size > MAX_EVENT_FILTER_DATA_SIZE {
		return EventFilterDescriptor{}, nil
	}

	return EventFilterDescriptor{
		Ptr:  uint64(uintptr(unsafe.Pointer(&utf16Str[0]))),
		Size: size,
		Type: EVENT_FILTER_TYPE_PACKAGE_APP_ID,
	}, &utf16Str
}
